apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: backend-build-run-
spec:
  pipelineRef:
    name: build-and-deploy-backend
  resources:
  - name: app-git
    resourceSpec:
      type: git
      params:
        - name: url
          value: $(resources.expenses-backend-git.url)
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: source-pvc
