---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-backend
spec:
  workspaces:
    - name: shared-workspace
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task.
  params:
    - name: git-url
      type: string
      default: "https://github.com/nmajorov/expenses-backend-quarkus.git"
    - name: git-revision
      type: string
      default: "master"

  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: $(params.git-url)
    workspaces:
    - name: output
      workspace: shared-workspace
