# create a pvc for workspace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi


---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: backend-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/nm-demo/expenses-backend-quarkus:latest
