---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clean-up
spec:
  steps:
    - name: clean
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/output
      script: |
        #!/usr/bin/env bash
        set -xe
        echo "remove existing checkout sources"
        find  /workspace/output/  -exec rm -rf {} \;

        echo "delete openshift test resources"
        oc delete  all --selector=app=postgresql-test
        # can't delete secrets
        oc delete secrets  --selector=app=postgresql-test

  workspaces:
    - name: output
      mountPath: /workspace/output
